### ISSUE TITLE
Generated matchExpression for PlacementRule has incorrect operator name of Exist instead of Exists

### ISSUE THREAD

**Issue by fgharo** [stolostron/policy-generator-plugin#53]
**Version(s):** 
PolicyGenerator - v1.7.0

**Description:**
The policy generator outputs an invalid matchExpression entry when setting an existence check in the placement.clusterSelectors field.

**Steps to reproduce:**
1. Prepare a directory that has the following manifests files:

cm.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: default
data:
  someKey: Some Key Value
```

policy-generator-config.yaml
```
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: cm-policy-generator
policyDefaults:
  namespace: default
policies:
  - name: cm-policy
    manifests:
      - path: cm.yaml
        complianceType: "musthave"
    remediationAction: inform
    placement:
      clusterSelectors:
        name: "local-cluster"
        some-label-exists: "" # expect this to be generated with Exists operator not Exist.
```
kustomization.yaml:
```
generators:
  - policy-generator-config.yaml
```
        
2. Run this command in the directory to generate the policy manifests:
`$ kustomize build --enable-alpha-plugins `

3. The following output will have a placement rule that has the bug.
```
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-cm-policy
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - local-cluster
    - key: some-label-exists
      operator: Exist
---
...
```

**Expected Result:**
A placement rule with a operator of Exists:
```
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-cm-policy
  namespace: default
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - local-cluster
    - key: some-label-exists
      operator: Exists
```
