### ISSUE TITLE
Error when using matchExpressions on clusterSelector PolicyGenerator/PolicySets

### ISSUE THREAD

**Issue by pazpuwi** [stolostron/policy-generator-plugin#90]
If you use **clusterSelectors** as mentioned in the [policy-generator-plugin](https://github.com/stolostron/policy-generator-plugin)/[docs](https://github.com/stolostron/policy-generator-plugin/tree/main/docs)/policygenerator-reference.yaml an Error occurs.

> E0116 10:11:28.062063 1 git_subscriber_item.go:155] failed to prepare resources to apply and there is no resource to apply. err: failure in plugin configured via /tmp/kust-plugin-config-471838647; exit status 1: exit status 1Subscription error.

Solution for us was to use **clusterSelector** insted of **clusterSelectors**

Example PolicySet:
```
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator
policySets:
- name: test
    placement:
      clusterSelector:
        matchExpressions:
          - key: foo
            operator: In
            values:
              - bar
```
