### ISSUE TITLE
Annotations on the PolicyGenerator CR causes failure

### ISSUE THREAD

**Issue by kenmoini** [stolostron/policy-generator-plugin#95]
So when creating a PolicyGenerator with a defined `.metadata.annotations` section causes it to fail generation.  Not sure if this is intended or not, but figured I'd give it a little drop here in case the common metav1 stuff should be in there.

The PolicyGenerator CR:

```yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: additional-trust-bundle-pg
  # Removing the annotations below allows this to build
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
placementBindingDefaults:
  name: additional-trust-bundle-pg-pb
policyDefaults:
  namespace: rhacm-policies
  placement:
    placementRuleName: all-openshift-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  policySets: 
    - global-base-configuration
policies:
  - name: additional-trust-bundles
    manifests:
      - path: base
```

The `kustomization.yml` file:

```yaml
generators:
  - policygenerator.yml
commonLabels:
  manifest-group: additional-trust-bundle
```

When running `kustomize build --enable-alpha-plugins` I get the following error:

```
$ kustomize build --enable-alpha-plugins

error processing the PolicyGenerator file '/var/folders/j0/wspjmhds20b2t63zpm9ycl4w0000gn/T/kust-plugin-config-2508743489': the PolicyGenerator configuration file is invalid: yaml: unmarshal errors:
  line 4: field annotations found but not defined { Name string "json:\"name,omitempty\" yaml:\"name,omitempty\"" }
Error: failure in plugin configured via /var/folders/j0/wspjmhds20b2t63zpm9ycl4w0000gn/T/kust-plugin-config-2508743489; exit status 1: exit status 1
```

Removing the annotations from the PolicyGenerator CR works, and then I can add them back as desired via `commonAnnotations` in the `kustomization.yml` so not crucial (in my case) that PolicyGenerator doesn't take annotations I guess, but may not be intended.

---

Working CRs

```yaml
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: additional-trust-bundle-pg
placementBindingDefaults:
  name: additional-trust-bundle-pg-pb
policyDefaults:
  namespace: rhacm-policies
  placement:
    placementRuleName: all-openshift-clusters
  remediationAction: enforce
  severity: high
  consolidateManifests: false # Put each object in its own ConfigurationPolicy in the Policy
  policySets: 
    - global-base-configuration
policies:
  - name: additional-trust-bundles
    manifests:
      - path: base
```

```yaml
generators:
  - policygenerator.yml
commonLabels:
  manifest-group: additional-trust-bundle

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
```
